r01lib: DigitalInOut Class Reference
DigitalInOut Class Reference
#include <io.h>
Public Member Functions
DigitalInOut (uint8_t pin_num, bool direction=kGPIO_DigitalInput, bool value=0)
~DigitalInOut ()
void value (bool value)
bool value (void)
void output (void)
void input (void)
void pin_mux (int mux)
DigitalInOut & operator= (bool v)
DigitalInOut & operator= (DigitalInOut &rhs)
operator bool ()
Public Member Functions inherited from Obj
Obj (bool done=false)
~Obj ()
Protected Attributes
uint8_t _pn
GPIO_Type * gpio_n
PORT_Type * port_n
uint8_t gpio_pin
Private Attributes
bool _dir
bool _value
Detailed Description
DigitalInOut class
A class for operating GPIO easy
Definition at line 222 of file io.h.
Constructor & Destructor Documentation
DigitalInOut()
DigitalInOut::DigitalInOut (uint8_t pin_num, bool direction = kGPIO_DigitalInput, bool value = 0)
Create a DigitalInOut instance with specified pins
Parameters
pin_num pin number
direction (option) direction setting
value (option) default value for output
Definition at line 69 of file io.cpp.
References _pn, _value, _gpio_pin::base, gpio_n, gpio_type, _gpio_pin::pin, pins, port_n, port_type, and value().
~DigitalInOut()
DigitalInOut::~DigitalInOut ()
Destractor
Definition at line 85 of file io.cpp.
Member Function Documentation
input()
void DigitalInOut::input (void)
Pin direction to set as in
Definition at line 114 of file io.cpp.
References _dir.
operator bool()
DigitalInOut::operator bool ()
A short hand for reading pins
Definition at line 135 of file io.cpp.
operator=() [1/2]
DigitalInOut & DigitalInOut::operator= (bool v)
A short hand for setting pins
Definition at line 124 of file io.cpp.
References value().
operator=() [2/2]
DigitalInOut & DigitalInOut::operator= (DigitalInOut & rhs)
Definition at line 130 of file io.cpp.
output()
void DigitalInOut::output (void)
Pin direction to set as output
Definition at line 109 of file io.cpp.
References _dir.
pin_mux()
void DigitalInOut::pin_mux (int mux)
Pin mux setting This interface is provided to other class drivers to change pin config dynamically
Definition at line 119 of file io.cpp.
References port_n.
value() [1/2]
void DigitalInOut::value (bool value)
Pin output seting
Parameters
value setting output
Definition at line 87 of file io.cpp.
References _dir, _pn, _value, gpio_n, pins, and value().
value() [2/2]
bool DigitalInOut::value (void)
Pin input state read
Returns
pin state
Definition at line 98 of file io.cpp.
References _dir, _pn, _value, gpio_n, and pins.
Member Data Documentation
_dir
bool DigitalInOut::_dir private
Definition at line 278 of file io.h.
_pn
uint8_t DigitalInOut::_pn protected
Definition at line 272 of file io.h.
_value
bool DigitalInOut::_value private
Definition at line 279 of file io.h.
gpio_n
GPIO_Type* DigitalInOut::gpio_n protected
Definition at line 273 of file io.h.
gpio_pin
uint8_t DigitalInOut::gpio_pin protected
Definition at line 275 of file io.h.
port_n
PORT_Type* DigitalInOut::port_n protected
Definition at line 274 of file io.h.
The documentation for this class was generated from the following files:
io.h
io.cpp