r01lib: I3C Class Reference
I3C Class Reference
#include <i3c.h>
Public Types
enum MODE { I3C_MODE = kI3C_TypeI3CSdr , I2C_MODE = kI3C_TypeI2C , I3CDDR_MODE = kI3C_TypeI3CDdr }
enum FREQ { OD_FREQ = 4000000UL , PP_FREQ = 12500000UL , DEFAULT_FREQ_SETTING = 0 }
enum MISC { BROADCAST_ADDR = 0x7E , PID_LENGTH = 6 }
Public Types inherited from I2C
enum STOP_CONDITION { STOP = true , NO_STOP = false }
enum FREQ { FREQ = 400000UL }
Public Member Functions
I3C (int sda, int scl, uint32_t i2c_freq=I2C::FREQ, uint32_t i3c_od_freq=OD_FREQ, uint32_t i3c_pp_freq=PP_FREQ)
~I3C ()
void frequency (uint32_t i2c_freq, uint32_t i3c_od_freq, uint32_t i3c_pp_freq)
void frequency (void)
void mode (MODE mode)
status_t write (uint8_t targ, const uint8_t *dp, int length, bool stop=STOP)
status_t read (uint8_t targ, uint8_t *dp, int length, bool stop=STOP)
status_t reg_write (uint8_t targ, uint8_t reg, const uint8_t *dp, int length, bool stop=STOP)
status_t reg_read (uint8_t targ, uint8_t reg, uint8_t *dp, int length, bool stop=STOP)
uint8_t check_IBI (void)
void set_IBI_callback (i3c_func_ptr fp)
status_t ccc_broadcast (uint8_t ccc, const uint8_t *dp, uint8_t length, bool first_time=false)
status_t ccc_set (uint8_t ccc, uint8_t addr, uint8_t data)
status_t ccc_get (uint8_t ccc, uint8_t addr, uint8_t *dp, uint8_t length)
int DAA (const uint8_t *address_list, uint8_t list_length, i3c_device_info_t **device_list)
Public Member Functions inherited from I2C
I2C (int sda, int scl, bool no_hw=false)
~I2C ()
virtual void frequency (uint32_t frequency)
virtual status_t reg_write (uint8_t targ, uint8_t reg, const uint8_t *dp, int length)
virtual status_t reg_write (uint8_t targ, uint8_t reg, uint8_t data)
virtual status_t reg_read (uint8_t targ, uint8_t reg, uint8_t *dp, int length)
virtual uint8_t reg_read (uint8_t targ, uint8_t reg)
virtual status_t write (uint8_t targ, uint8_t data, bool stop=STOP)
virtual uint8_t read (uint8_t targ, bool stop=STOP)
Public Member Functions inherited from Obj
Obj (bool done=false)
~Obj ()
Static Public Member Functions
static void master_ibi_callback (I3C_Type *base, i3c_master_handle_t *handle, i3c_ibi_type_t ibiType, i3c_ibi_state_t ibiState)
static void master_callback (I3C_Type *base, i3c_master_handle_t *handle, status_t status, void *userData)
Private Member Functions
status_t xfer (i3c_direction_t dir, i3c_bus_type_t type, uint8_t targ, uint8_t *dp, int length, bool stop=STOP)
status_t reg_xfer (i3c_direction_t dir, i3c_bus_type_t type, uint8_t targ, uint8_t reg, uint8_t reg_length, uint8_t *dp, int length, bool stop=STOP)
Private Attributes
i3c_bus_type_t bus_type
i3c_master_config_t masterConfig
bool first_broadcast
Static Private Attributes
static const i3c_master_transfer_callback_t masterCallback
Additional Inherited Members
Public Attributes inherited from I2C
status_t last_status
Detailed Description
I3C class
A class for demonstrating I3C bus
Member Enumeration Documentation
FREQ
enum I3C::FREQ
constants for SCL frequency settings
Enumerator
OD_FREQ
PP_FREQ
DEFAULT_FREQ_SETTING
MISC
enum I3C::MISC
constants for miscellaneous setting
Enumerator
BROADCAST_ADDR
PID_LENGTH
MODE
enum I3C::MODE
constants for mode setting
Enumerator
I3C_MODE
I2C_MODE
I3CDDR_MODE
Constructor & Destructor Documentation
I3C()
I3C::I3C (int sda, int scl, uint32_t i2c_freq = I2C::FREQ, uint32_t i3c_od_freq = OD_FREQ, uint32_t i3c_pp_freq = PP_FREQ)
Create an I3C instance with specified pins
Parameters
sda pin number to connect SDA
scl pin number to connect SCL
i2c_freq (option) define default scl frequency while I2C operation
i3c_od_freq (option) define default scl frequency while I3C open-drain operation
i3c_pp_freq (option) define default scl frequency while I3C push-pull operation
References bus_type, EXAMPLE_MASTER, first_broadcast, g_i3c_m_handle, I2C_SCL, I2C_SDA, I3C_MASTER_CLOCK_FREQUENCY, I3C_SCL, I3C_SDA, masterCallback, masterConfig, OD_FREQ, panic(), DigitalInOut::pin_mux(), and PP_FREQ.
~I3C()
I3C::~I3C ()
Destractor to freeing I3C resource
References EXAMPLE_MASTER.
Member Function Documentation
ccc_broadcast()
status_t I3C::ccc_broadcast (uint8_t ccc, const uint8_t * dp, uint8_t length, bool first_time = false)
CCC broadcast
Parameters
ccc CCC command
dp data to send
length data length
Returns
status_t
References BROADCAST_ADDR, first_broadcast, frequency(), REG_RW_BUFFER_SIZE, and write().
ccc_get()
status_t I3C::ccc_get (uint8_t ccc, uint8_t addr, uint8_t * dp, uint8_t length) virtual
CCC get
Parameters
ccc CCC command
dp data to send
length data length
Returns
status_t
Reimplemented from I2C.
References BROADCAST_ADDR, I2C::NO_STOP, read(), and write().
ccc_set()
status_t I3C::ccc_set (uint8_t ccc, uint8_t addr, uint8_t data) virtual
CCC set
Parameters
ccc CCC command
data single byte data
Returns
status_t
Reimplemented from I2C.
References BROADCAST_ADDR, I2C::NO_STOP, and write().
check_IBI()
uint8_t I3C::check_IBI (void)
check IBI status
Returns
target address of IBI initiated device or zero if no event happened
References g_ibiAddress, and g_ibiWonFlag.
DAA()
int I3C::DAA (const uint8_t * address_list, uint8_t list_length, i3c_device_info_t ** device_list)
perform DAA procedure
Parameters
address_list new address list to be assigned
list_length address list length
device_list pointer to i3c_device_info_t array which is dealeared as static array in I3C driver
Returns
int for number of devices which has newly assigned addresses (max 10)
References EXAMPLE_MASTER.
frequency() [1/2]
void I3C::frequency (uint32_t i2c_freq, uint32_t i3c_od_freq, uint32_t i3c_pp_freq)
Frequency settings
Parameters
i2c_freq (option) define default scl frequency while I2C operation
i3c_od_freq (option) define default scl frequency while I3C open-drain operation
i3c_pp_freq (option) define default scl frequency while I3C push-pull operation
Note
use zero or I3C_DEFAULT_FREQ to set default frequency
References EXAMPLE_MASTER, I3C_MASTER_CLOCK_FREQUENCY, and masterConfig.
frequency() [2/2]
void I3C::frequency (void)
All frequency settings reverted to default
References EXAMPLE_MASTER, I3C_MASTER_CLOCK_FREQUENCY, and masterConfig.
master_callback()
void I3C::master_callback (I3C_Type * base, i3c_master_handle_t * handle, status_t status, void * userData) static
master_ibi_callback interface function for SDK
References g_completionStatus, and g_masterCompletionFlag.
master_ibi_callback()
void I3C::master_ibi_callback (I3C_Type * base, i3c_master_handle_t * handle, i3c_ibi_type_t ibiType, i3c_ibi_state_t ibiState) static
master_ibi_callback interface function for SDK
References g_ibi_callback, g_ibiAddress, g_ibiBuff, g_ibiUserBuff, g_ibiUserBuffUsed, and g_ibiWonFlag.
mode()
void I3C::mode (MODE mode)
mode setting I3C bus is configured to I3C-SDR, I3C-DDR or I2C
Parameters
mode kI3C_TypeI3CSdr, kI3C_TypeI2C or kI3C_TypeI3CDdr
References bus_type, and mode().
read()
status_t I3C::read (uint8_t targ, uint8_t * dp, int length, bool stop = STOP) virtual
read transaction
Parameters
targ target address
dp data to write
length data length
stop (option) generate STOP condition: "false" to make repeated-start in next transaction
Returns
status_t
Reimplemented from I2C.
References bus_type, and xfer().
reg_read()
status_t I3C::reg_read (uint8_t targ, uint8_t reg, uint8_t * dp, int length, bool stop = STOP)
Register read (multiple byte data) provideds interface for register read
Parameters
targ target address
reg register address
dp data to write
length data length
Returns
status_t
References bus_type, and reg_xfer().
reg_write()
status_t I3C::reg_write (uint8_t targ, uint8_t reg, const uint8_t * dp, int length, bool stop = STOP)
Register write (multiple byte data) provideds interface for register write
Parameters
targ target address
reg register address
dp data to write
length data length
Returns
status_t
References bus_type, and reg_xfer().
reg_xfer()
status_t I3C::reg_xfer (i3c_direction_t dir, i3c_bus_type_t type, uint8_t targ, uint8_t reg, uint8_t reg_length, uint8_t * dp, int length, bool stop = STOP) private
References EXAMPLE_MASTER.
set_IBI_callback()
void I3C::set_IBI_callback (i3c_func_ptr fp)
set IBI callback function
Returns
target address of IBI initiated device or zero if no event happened
References g_ibi_callback.
write()
status_t I3C::write (uint8_t targ, const uint8_t * dp, int length, bool stop = STOP) virtual
write transaction
Parameters
targ target address
dp data to write
length data length
stop (option) generate STOP condition: "false" to make repeated-start in next transaction
Returns
status_t
Reimplemented from I2C.
References bus_type, and xfer().
xfer()
status_t I3C::xfer (i3c_direction_t dir, i3c_bus_type_t type, uint8_t targ, uint8_t * dp, int length, bool stop = STOP) private
References bus_type, and reg_xfer().
Member Data Documentation
bus_type
i3c_bus_type_t I3C::bus_type private
first_broadcast
bool I3C::first_broadcast private
masterCallback
const i3c_master_transfer_callback_t I3C::masterCallback static private
Initial value:
= {
    .slave2Master       = NULL,
    .ibiCallback        = master_ibi_callback,
    .transferComplete   = master_callback
}
masterConfig
i3c_master_config_t I3C::masterConfig private
The documentation for this class was generated from the following files:
i3c.h
i3c.cpp