r01lib: I2C Class Reference
I2C Class Reference
#include <i2c.h>
Public Types
enum STOP_CONDITION { STOP = true , NO_STOP = false }
enum FREQ { FREQ = 400000UL }
Public Member Functions
I2C (int sda, int scl, bool no_hw=false)
~I2C ()
virtual void frequency (uint32_t frequency)
virtual status_t reg_write (uint8_t targ, uint8_t reg, const uint8_t *dp, int length)
virtual status_t reg_write (uint8_t targ, uint8_t reg, uint8_t data)
virtual status_t reg_read (uint8_t targ, uint8_t reg, uint8_t *dp, int length)
virtual uint8_t reg_read (uint8_t targ, uint8_t reg)
virtual status_t write (uint8_t address, const uint8_t *dp, int length, bool stop=STOP)
virtual status_t write (uint8_t targ, uint8_t data, bool stop=STOP)
virtual status_t read (uint8_t address, uint8_t *dp, int length, bool stop=STOP)
virtual uint8_t read (uint8_t targ, bool stop=STOP)
virtual status_t ccc_set (uint8_t ccc, uint8_t addr, uint8_t data)
virtual status_t ccc_get (uint8_t ccc, uint8_t addr, uint8_t *dp, uint8_t length)
Public Attributes
status_t last_status
Private Attributes
lpi2c_master_config_t masterConfig
Detailed Description
I2C class
A class for demonstrating I2C bus
Member Enumeration Documentation
FREQ
enum I2C::FREQ
constants for SCL frequency settings
Enumerator
FREQ
STOP_CONDITION
enum I2C::STOP_CONDITION
constants for STOP-cindition setting
Enumerator
STOP
NO_STOP
Constructor & Destructor Documentation
I2C()
I2C::I2C (int sda, int scl, bool no_hw = false)
Create an I2C instance with specified pins
Parameters
sda pin number to connect SDA
scl pin number to connect SCL
no_hw (option) flag for I3C. I3C constructor will set this flag to avoid set hardware for both I3C and I2C
References EXAMPLE_I2C_MASTER, I2C_SCL, I2C_SDA, I3C_SCL, I3C_SDA, LPI2C_MASTER_CLOCK_FREQUENCY, masterConfig, MB_MOSI, MB_SCK, MB_SCL, MB_SDA, panic(), and DigitalInOut::pin_mux().
~I2C()
I2C::~I2C ()
Destractor to freeing I3C resource
References EXAMPLE_I2C_MASTER.
Member Function Documentation
ccc_get()
status_t I2C::ccc_get (uint8_t ccc, uint8_t addr, uint8_t * dp, uint8_t length) virtual
method for I3C class compatibility (dummy method) Does notheing but clearing data buffer and return kStatus_Success This method is for just make easy device class using I3C
Parameters
ccc CCC command
dp data to send
length data length
Returns
status_t
Reimplemented in I3C.
ccc_set()
status_t I2C::ccc_set (uint8_t ccc, uint8_t addr, uint8_t data) virtual
method for I3C class compatibility (dummy method) Does notheing but return kStatus_Success This method is for just make easy device class using I3C
Parameters
ccc CCC command
data single byte data
Returns
kStatus_Success
Reimplemented in I3C.
frequency()
void I2C::frequency (uint32_t frequency) virtual
set SCL frequency
Parameters
frequency integer value in "Hz"
References EXAMPLE_I2C_MASTER, frequency(), and LPI2C_MASTER_CLOCK_FREQUENCY.
read() [1/2]
status_t I2C::read (uint8_t address, uint8_t * dp, int length, bool stop = STOP) virtual
read transactiond (multiple byte data)
Parameters
targ target address
dp data to write
length data length
stop (option) generate STOP condition: "false" to make repeated-start in next transaction
Returns
status_t
Reimplemented in I3C.
References EXAMPLE_I2C_MASTER.
read() [2/2]
uint8_t I2C::read (uint8_t targ, bool stop = STOP) virtual
read transaction (single byte data) provideds interface for register read returns a single byte data status can be checked by last_status variable
Parameters
targ target address
stop (option) generate STOP condition: "false" to make repeated-start in next transaction
Returns
data
References last_status, and read().
reg_read() [1/2]
uint8_t I2C::reg_read (uint8_t targ, uint8_t reg) virtual
Register read (single byte data) provideds interface for register read returns a single byte data status can be checked by last_status variable
Parameters
targ target address
reg register address
Returns
read data
References last_status, NO_STOP, read(), and write().
reg_read() [2/2]
status_t I2C::reg_read (uint8_t targ, uint8_t reg, uint8_t * dp, int length) virtual
Register read (multiple byte data) provideds interface for register read
Parameters
targ target address
reg register address
dp data to write
length data length
Returns
status_t
References last_status, NO_STOP, read(), and write().
reg_write() [1/2]
status_t I2C::reg_write (uint8_t targ, uint8_t reg, const uint8_t * dp, int length) virtual
Register write (multiple byte data) provideds interface for register write
Parameters
targ target address
reg register address
dp data to write
length data length
Returns
status_t
References last_status, REG_RW_BUFFER_SIZE, and write().
reg_write() [2/2]
status_t I2C::reg_write (uint8_t targ, uint8_t reg, uint8_t data) virtual
Register write (single byte data) provideds interface for register write
Parameters
targ target address
reg register address
data data to write
Returns
status_t
References write().
write() [1/2]
status_t I2C::write (uint8_t address, const uint8_t * dp, int length, bool stop = STOP) virtual
write transactiond (multiple byte data)
Parameters
targ target address
dp data to write
length data length
stop (option) generate STOP condition: "false" to make repeated-start in next transaction
Returns
status_t
Reimplemented in I3C.
References EXAMPLE_I2C_MASTER.
write() [2/2]
status_t I2C::write (uint8_t targ, uint8_t data, bool stop = STOP) virtual
write transactiond (single byte data)
Parameters
targ target address
data data to write
stop (option) generate STOP condition: "false" to make repeated-start in next transaction
Returns
status_t
References write().
Member Data Documentation
last_status
status_t I2C::last_status
variable for reporting last state
masterConfig
lpi2c_master_config_t I2C::masterConfig private
The documentation for this class was generated from the following files:
i2c.h
i2c.cpp